#!/usr/bin/env bash
# conduct-stats.sh — Reads the conduct-violations.jsonl and prints a summary.
#
# Usage:
#   bash infra/hooks/conduct-stats.sh           # Full summary (stdout, no side-effects)
#   bash infra/hooks/conduct-stats.sh --dream   # Compact 7-day JSON digest for agent-dreaming
#   bash infra/hooks/conduct-stats.sh --check   # Check metrics vs targets; exit 1 + write escalation on breach
#   bash infra/hooks/conduct-stats.sh --md      # Write human dashboard to $VAULT/02_Areas/Conduct.md
#
# Output: plain text or JSON to stdout (--dream, default).
#         --check:  exits 0 (clean) or 1 (breach). Breach writes to Important/escalations/.
#         --md:     writes 02_Areas/Conduct.md; exits 0.
# Idempotent for all modes. Append-only log; never modified.
#
# Dependencies: jq (preferred) OR python3 stdlib (automatic fallback).
# bash -n clean; python3 -m py_compile clean.

set -uo pipefail

# ── Paths ────────────────────────────────────────────────────────────────────

VAULT="${VAULT_ROOT:?Set VAULT_ROOT to your vault path}"
VIOLATIONS_FILE="$VAULT/_agent_state/_conduct/conduct-violations.jsonl"
ESCALATIONS_DIR="$VAULT/Important/escalations"
CONDUCT_MD="$VAULT/02_Areas/Conduct.md"
METRICS_FILE="$VAULT/infra/conduct/conduct-success-metrics.md"
FP_LOG="$VAULT/_agent_state/_conduct/false-positive-log.jsonl"
DREAM_DIGEST="$VAULT/_agent_state/_conduct/dream-digest.json"

# ── Mode ─────────────────────────────────────────────────────────────────────

DREAM_MODE=0
CHECK_MODE=0
MD_MODE=0
[[ "${1:-}" == "--dream" ]] && DREAM_MODE=1
[[ "${1:-}" == "--check" ]] && CHECK_MODE=1
[[ "${1:-}" == "--md" ]]    && MD_MODE=1

# ── Handle missing / empty file ───────────────────────────────────────────────

if [[ ! -f "$VIOLATIONS_FILE" ]] || [[ ! -s "$VIOLATIONS_FILE" ]]; then
  if [[ $DREAM_MODE -eq 1 ]]; then
    printf '{"dream":true,"period_days":7,"generated":"%s","status":"no_data","top_violations":[],"agent_profiles":[],"high_severity":[]}\n' \
      "$(date -Iseconds)"
  elif [[ $CHECK_MODE -eq 1 ]]; then
    printf 'conduct-stats --check: log missing or empty — all violation-count metrics pass (0 violations).\n'
    python3 - "$DREAM_DIGEST" "$ESCALATIONS_DIR" <<'CHECK_NODATA'
import sys, os, datetime

dream_digest = sys.argv[1]
escalations_dir = sys.argv[2]
os.makedirs(escalations_dir, exist_ok=True)
now = datetime.datetime.now(datetime.timezone.utc)
breaches = []

# Metric 5 — dream loop cadence (48h hard limit)
if os.path.isfile(dream_digest):
    mtime = datetime.datetime.fromtimestamp(os.path.getmtime(dream_digest), tz=datetime.timezone.utc)
    age_h = (now - mtime).total_seconds() / 3600
    if age_h > 48:
        breaches.append(f"dream-loop-cadence: digest is {age_h:.1f}h old (threshold 48h)")
else:
    breaches.append("dream-loop-cadence: dream-digest.json not found — dream loop has never run")

if breaches:
    date_str = now.strftime("%Y-%m-%d")
    esc_file = os.path.join(escalations_dir, f"conduct-breach-{date_str}.md")
    line = "[BREACH] " + "; ".join(breaches) + f". Checked: {now.isoformat(timespec='seconds')}"
    with open(esc_file, "a", encoding="utf-8") as fh:
        fh.write(line + "\n")
    print(line, file=sys.stderr)
    sys.exit(1)
sys.exit(0)
CHECK_NODATA
  elif [[ $MD_MODE -eq 1 ]]; then
    mkdir -p "$(dirname "$CONDUCT_MD")"
    python3 - "$CONDUCT_MD" <<'MD_NODATA'
import sys, datetime
out = sys.argv[1]
now = datetime.datetime.now().astimezone().isoformat(timespec="seconds")
content = f"""---
type: dashboard
topic: conduct
generated: {now}
---

# Conduct Dashboard

> Generated by `conduct-stats.sh --md` on {now}.

**No violations on record.** The log is empty or missing — the conduct system is clean.

| Metric | Value |
|---|---|
| Total violations | 0 |
| Last 7 days | 0 |
| High severity | 0 |
"""
with open(out, "w", encoding="utf-8") as fh:
    fh.write(content)
print(f"conduct-stats --md: wrote {out}")
MD_NODATA
  else
    printf 'conduct-stats: no violations on record (file missing or empty).\n'
    printf 'File: %s\n' "$VIOLATIONS_FILE"
  fi
  exit 0
fi

# ── Choose implementation: jq or python3 ─────────────────────────────────────

if command -v jq >/dev/null 2>&1; then
  _IMPL="jq"
else
  _IMPL="python3"
fi

# ════════════════════════════════════════════════════════════════════════════
# JQ IMPLEMENTATION
# ════════════════════════════════════════════════════════════════════════════

run_jq_full() {
  local f="$VIOLATIONS_FILE"

  printf '\n══════════════════════════════════════════════════════\n'
  printf '  CONDUCT VIOLATIONS SUMMARY\n'
  printf '  File: %s\n' "$f"
  printf '  Generated: %s\n' "$(date -Iseconds)"
  printf '══════════════════════════════════════════════════════\n\n'

  local total
  total=$(jq -s 'length' "$f")
  printf 'TOTAL VIOLATIONS: %s\n\n' "$total"

  printf '── BY SOURCE ─────────────────────────────────────────\n'
  jq -rs '[.[] | .source] | group_by(.) | map({source: .[0], count: length}) | sort_by(-.count) | .[] | "\(.count)  \(.source)"' "$f"
  printf '\n'

  printf '── BY RULE ───────────────────────────────────────────\n'
  jq -rs '[.[] | .rule] | group_by(.) | map({rule: .[0], count: length}) | sort_by(-.count) | .[] | "\(.count)  \(.rule)"' "$f"
  printf '\n'

  printf '── BY SEVERITY ───────────────────────────────────────\n'
  jq -rs '[.[] | .severity] | group_by(.) | map({sev: .[0], count: length}) | sort_by(-.count) | .[] | "\(.count)  \(.sev)"' "$f"
  printf '\n'

  printf '── BY AGENT ──────────────────────────────────────────\n'
  jq -rs '[.[] | .agent] | group_by(.) | map({agent: .[0], count: length}) | sort_by(-.count) | .[] | "\(.count)  \(.agent)"' "$f"
  printf '\n'

  printf '── LAST 10 (newest first) ────────────────────────────\n'
  jq -rs 'sort_by(.ts) | reverse | .[0:10] | .[] | "[\(.ts)]  [\(.severity)]  \(.agent)  \(.rule)\n  \(.detail)\n  file: \(.file // "null")"' "$f"
  printf '\n══════════════════════════════════════════════════════\n\n'
}

run_jq_dream() {
  local f="$VIOLATIONS_FILE"
  local cutoff
  cutoff=$(python3 -c "
import datetime
d = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=7)
print(d.isoformat(timespec='seconds'))
")

  jq -rs --arg cutoff "$cutoff" '
    map(select(.ts >= $cutoff)) as $window |
    {
      dream: true,
      period_days: 7,
      generated: now | todate,
      total_in_window: ($window | length),
      top_violations: (
        $window
        | group_by(.rule)
        | map({
            rule: .[0].rule,
            count: length,
            dominant_severity: (group_by(.severity) | sort_by(-length) | .[0][0].severity),
            agents: (map(.agent) | unique),
            example: .[0].detail
          })
        | sort_by(-.count)
        | .[0:5]
      ),
      agent_profiles: (
        $window
        | group_by(.agent)
        | map({
            agent: .[0].agent,
            count: length,
            top_rule: (group_by(.rule) | sort_by(-length) | .[0][0].rule),
            high_count: (map(select(.severity == "high")) | length)
          })
        | sort_by(-.count)
      ),
      high_severity_last7: (
        $window
        | map(select(.severity == "high"))
        | sort_by(.ts) | reverse
        | .[0:10]
        | map({ts: .ts, agent: .agent, rule: .rule, detail: .detail, file: .file})
      ),
      rules_with_3plus_same_day: (
        $window
        | group_by(.ts[0:10])
        | map(
            {
              day: .[0].ts[0:10],
              rules: (group_by(.rule) | map(select(length >= 3)) | map({rule: .[0].rule, count: length}))
            }
          )
        | map(select(.rules | length > 0))
      )
    }
  ' "$f"
}

# ════════════════════════════════════════════════════════════════════════════
# PYTHON3 IMPLEMENTATION (stdlib only)
# ════════════════════════════════════════════════════════════════════════════

run_python_full() {
  python3 - "$VIOLATIONS_FILE" <<'PYEOF'
import sys, json, collections, datetime

path = sys.argv[1]

records = []
with open(path, encoding="utf-8") as fh:
    for lineno, raw in enumerate(fh, 1):
        raw = raw.strip()
        if not raw:
            continue
        try:
            records.append(json.loads(raw))
        except json.JSONDecodeError as exc:
            print(f"[WARN] line {lineno} is not valid JSON: {exc}", file=sys.stderr)

sep = "══════════════════════════════════════════════════════"
print(f"\n{sep}")
print("  CONDUCT VIOLATIONS SUMMARY")
print(f"  File: {path}")
print(f"  Generated: {datetime.datetime.now().astimezone().isoformat(timespec='seconds')}")
print(f"{sep}\n")
print(f"TOTAL VIOLATIONS: {len(records)}\n")

def top_counts(records, key, title):
    counts = collections.Counter(r.get(key, "unknown") for r in records)
    print(f"── {title} {'─' * (50 - len(title) - 4)}")
    for val, cnt in counts.most_common():
        print(f"  {cnt:>4}  {val}")
    print()

top_counts(records, "source", "BY SOURCE")
top_counts(records, "rule",   "BY RULE")
top_counts(records, "severity","BY SEVERITY")
top_counts(records, "agent",  "BY AGENT")

print("── LAST 10 (newest first) ────────────────────────────")
sorted_recs = sorted(records, key=lambda r: r.get("ts", ""), reverse=True)
for r in sorted_recs[:10]:
    ts       = r.get("ts", "?")
    sev      = r.get("severity", "?")
    agent    = r.get("agent", "?")
    rule     = r.get("rule", "?")
    detail   = r.get("detail", "?")
    file_    = r.get("file") or "null"
    print(f"[{ts}]  [{sev}]  {agent}  {rule}")
    print(f"  {detail}")
    print(f"  file: {file_}")
print(f"\n{sep}\n")
PYEOF
}

run_python_dream() {
  python3 - "$VIOLATIONS_FILE" <<'PYEOF'
import sys, json, collections, datetime

path = sys.argv[1]
now = datetime.datetime.now(datetime.timezone.utc)
cutoff = now - datetime.timedelta(days=7)

records = []
with open(path, encoding="utf-8") as fh:
    for raw in fh:
        raw = raw.strip()
        if not raw:
            continue
        try:
            records.append(json.loads(raw))
        except json.JSONDecodeError:
            pass

window = [r for r in records if r.get("ts", "") >= cutoff.isoformat(timespec="seconds")]

rule_groups = collections.defaultdict(list)
for r in window:
    rule_groups[r.get("rule", "unknown")].append(r)

top_violations = []
for rule, items in sorted(rule_groups.items(), key=lambda x: -len(x[1]))[:5]:
    sev_counts = collections.Counter(r.get("severity", "?") for r in items)
    dominant_sev = sev_counts.most_common(1)[0][0] if sev_counts else "?"
    agents = list({r.get("agent", "unknown") for r in items})
    top_violations.append({
        "rule": rule,
        "count": len(items),
        "dominant_severity": dominant_sev,
        "agents": agents,
        "example": items[0].get("detail", "?"),
    })

agent_groups = collections.defaultdict(list)
for r in window:
    agent_groups[r.get("agent", "unknown")].append(r)

agent_profiles = []
for agent, items in sorted(agent_groups.items(), key=lambda x: -len(x[1])):
    rule_ctr = collections.Counter(r.get("rule", "?") for r in items)
    top_rule = rule_ctr.most_common(1)[0][0] if rule_ctr else "?"
    high_cnt = sum(1 for r in items if r.get("severity") == "high")
    agent_profiles.append({
        "agent": agent,
        "count": len(items),
        "top_rule": top_rule,
        "high_count": high_cnt,
    })

high_sev = sorted(
    [r for r in window if r.get("severity") == "high"],
    key=lambda r: r.get("ts", ""),
    reverse=True,
)[:10]
high_list = [{"ts": r.get("ts"), "agent": r.get("agent"), "rule": r.get("rule"),
              "detail": r.get("detail"), "file": r.get("file")} for r in high_sev]

day_rule = collections.defaultdict(lambda: collections.defaultdict(int))
for r in window:
    day = r.get("ts", "")[:10]
    rule = r.get("rule", "?")
    day_rule[day][rule] += 1

rules_3plus_day = []
for day, rule_counts in sorted(day_rule.items()):
    spikes = [{"rule": rule, "count": cnt} for rule, cnt in rule_counts.items() if cnt >= 3]
    if spikes:
        rules_3plus_day.append({"day": day, "rules": spikes})

digest = {
    "dream": True,
    "period_days": 7,
    "generated": now.isoformat(timespec="seconds"),
    "total_in_window": len(window),
    "top_violations": top_violations,
    "agent_profiles": agent_profiles,
    "high_severity_last7": high_list,
    "rules_with_3plus_same_day": rules_3plus_day,
}
print(json.dumps(digest, ensure_ascii=False, indent=2))
PYEOF
}

# ════════════════════════════════════════════════════════════════════════════
# --check MODE
# ════════════════════════════════════════════════════════════════════════════

run_check() {
  python3 - \
    "$VIOLATIONS_FILE" \
    "$FP_LOG" \
    "$DREAM_DIGEST" \
    "$ESCALATIONS_DIR" \
    "$VAULT" \
    <<'CHECK_PY'
import sys, json, os, datetime, collections

violations_path = sys.argv[1]
fp_log_path     = sys.argv[2]
dream_digest    = sys.argv[3]
escalations_dir = sys.argv[4]
vault           = sys.argv[5]

os.makedirs(escalations_dir, exist_ok=True)

now = datetime.datetime.now(datetime.timezone.utc)
today_str = now.strftime("%Y-%m-%d")

records = []
with open(violations_path, encoding="utf-8") as fh:
    for raw in fh:
        raw = raw.strip()
        if not raw:
            continue
        try:
            records.append(json.loads(raw))
        except json.JSONDecodeError:
            pass

fp_records = []
if os.path.isfile(fp_log_path):
    with open(fp_log_path, encoding="utf-8") as fh:
        for raw in fh:
            raw = raw.strip()
            if not raw:
                continue
            try:
                fp_records.append(json.loads(raw))
            except json.JSONDecodeError:
                pass

cutoff_7d  = (now - datetime.timedelta(days=7)).isoformat(timespec="seconds")
cutoff_30d = (now - datetime.timedelta(days=30)).isoformat(timespec="seconds")

window_7d  = [r for r in records if r.get("ts", "") >= cutoff_7d]
window_30d = [r for r in records if r.get("ts", "") >= cutoff_30d]

oldest_ts = min((r.get("ts", "") for r in records), default="")
has_history_9w = bool(oldest_ts) and oldest_ts < (now - datetime.timedelta(days=63)).isoformat(timespec="seconds")

count_7d = len(window_7d)

cutoff_14d = (now - datetime.timedelta(days=14)).isoformat(timespec="seconds")
window_prior_7d = [r for r in records if cutoff_14d <= r.get("ts", "") < cutoff_7d]
count_prior_7d = len(window_prior_7d)
delta = count_7d - count_prior_7d

breaches = []

if count_7d > 10 and delta > 0:
    breaches.append(
        f"violations-per-week: {count_7d} in last 7d (threshold 10), delta={delta:+d} (rising)"
    )
if has_history_9w and count_7d > 5:
    breaches.append(
        f"violations-per-week (steady-state): {count_7d} in last 7d (threshold 5)"
    )

fp_30d = [r for r in fp_records if r.get("ts", "") >= cutoff_30d]
hook_flags_30d = [
    r for r in window_30d
    if r.get("source", "") in ("md-write-hook", "injection-scan")
]
total_flags = len(hook_flags_30d)
fp_count = len(fp_30d)
if total_flags > 0:
    fp_rate = fp_count / total_flags
    if fp_rate >= 0.05:
        breaches.append(
            f"false-positive-rate: {fp_rate*100:.1f}% over 30d ({fp_count}/{total_flags}) — threshold 5%"
        )

agent_state_dir = os.path.join(vault, "_agent_state")
theta_breaches = []
if os.path.isdir(agent_state_dir):
    for entry in sorted(os.listdir(agent_state_dir)):
        rep_path = os.path.join(agent_state_dir, entry, "reputation.json")
        if not os.path.isfile(rep_path):
            continue
        try:
            with open(rep_path, encoding="utf-8") as fh:
                rep = json.load(fh)
        except (json.JSONDecodeError, IOError):
            continue
        theta = rep.get("theta") or rep.get("reputation_theta")
        if theta is None:
            continue
        run_count = rep.get("run_count") or rep.get("runs", 0) or 0
        last_active = rep.get("last_active", "")
        is_active = run_count >= 10 or (last_active >= cutoff_30d)
        if not is_active:
            continue
        if float(theta) < 0.85:
            theta_breaches.append(f"{entry} theta={theta}")

if theta_breaches:
    breaches.append(
        "reputation-theta-below-floor: " + ", ".join(theta_breaches)
    )

if os.path.isfile(dream_digest):
    mtime = datetime.datetime.fromtimestamp(
        os.path.getmtime(dream_digest), tz=datetime.timezone.utc
    )
    age_h = (now - mtime).total_seconds() / 3600
    if age_h > 48:
        breaches.append(
            f"dream-loop-cadence: digest is {age_h:.1f}h old (threshold 48h)"
        )
else:
    breaches.append(
        "dream-loop-cadence: dream-digest.json not found — dream loop has never run"
    )

if breaches:
    esc_file = os.path.join(escalations_dir, f"conduct-breach-{today_str}.md")
    ts_str = now.isoformat(timespec="seconds")
    with open(esc_file, "a", encoding="utf-8") as fh:
        for b in breaches:
            line = f"[BREACH] {b}. Checked: {ts_str}\n"
            fh.write(line)
            print(line.rstrip(), file=sys.stderr)
    print(f"conduct-stats --check: {len(breaches)} breach(es) — see {esc_file}", file=sys.stderr)
    sys.exit(1)
else:
    print(
        f"conduct-stats --check: OK — "
        f"7d violations={count_7d}, fp_rate={fp_count}/{max(total_flags,1)}, "
        f"no theta breaches, dream digest present."
    )
    sys.exit(0)
CHECK_PY
}

# ════════════════════════════════════════════════════════════════════════════
# --md MODE
# ════════════════════════════════════════════════════════════════════════════

run_md() {
  python3 - "$VIOLATIONS_FILE" "$CONDUCT_MD" <<'MD_PY'
import sys, json, collections, datetime, os

violations_path = sys.argv[1]
out_path        = sys.argv[2]

os.makedirs(os.path.dirname(out_path), exist_ok=True)

now = datetime.datetime.now().astimezone()
now_iso = now.isoformat(timespec="seconds")
now_str = now.strftime("%Y-%m-%d %H:%M %Z")

records = []
with open(violations_path, encoding="utf-8") as fh:
    for lineno, raw in enumerate(fh, 1):
        raw = raw.strip()
        if not raw:
            continue
        try:
            records.append(json.loads(raw))
        except json.JSONDecodeError:
            pass

cutoff_7d = (datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=7)).isoformat(timespec="seconds")
window_7d = [r for r in records if r.get("ts", "") >= cutoff_7d]

total = len(records)
total_7d = len(window_7d)
high_total = sum(1 for r in records if r.get("severity") == "high")
high_7d    = sum(1 for r in window_7d if r.get("severity") == "high")

cutoff_14d = (datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=14)).isoformat(timespec="seconds")
prior_7d = [r for r in records if cutoff_14d <= r.get("ts", "") < cutoff_7d]
delta_7d = total_7d - len(prior_7d)
delta_str = f"+{delta_7d}" if delta_7d > 0 else str(delta_7d)
if delta_7d < 0:
    trend_emoji = "(improving)"
elif delta_7d == 0:
    trend_emoji = "(flat)"
else:
    trend_emoji = "(worsening)"

def top_table(records, key, header, max_rows=10):
    counts = collections.Counter(r.get(key, "unknown") for r in records)
    rows = [f"| {v} | {c} |" for v, c in counts.most_common(max_rows)]
    if not rows:
        return f"| — | — |\n"
    return "\n".join(rows) + "\n"

by_rule_all   = top_table(records,   "rule",     "Rule (all-time)")
by_rule_7d    = top_table(window_7d, "rule",     "Rule (7d)")
by_source_all = top_table(records,   "source",   "Source")
by_sev_all    = top_table(records,   "severity", "Severity")
by_agent_all  = top_table(records,   "agent",    "Agent")

sorted_recs = sorted(records, key=lambda r: r.get("ts", ""), reverse=True)
last10_rows = []
for r in sorted_recs[:10]:
    ts     = r.get("ts", "?")
    sev    = r.get("severity", "?")
    agent  = r.get("agent", "?")
    rule   = r.get("rule", "?")
    detail = r.get("detail", "?")[:80].replace("|", "·")
    last10_rows.append(f"| {ts} | {sev} | {agent} | {rule} | {detail} |")
last10_block = "\n".join(last10_rows) if last10_rows else "| — | — | — | — | — |"

content = f"""---
type: dashboard
topic: conduct
generated: {now_iso}
---

# Conduct Dashboard

> Auto-generated by `conduct-stats.sh --md`. Last updated: **{now_str}**.
> Source: `_agent_state/_conduct/conduct-violations.jsonl` — {total} total records.

---

## Summary

| Metric | All-time | Last 7 days | 7d delta |
|---|---|---|---|
| Total violations | {total} | {total_7d} | {delta_str} {trend_emoji} |
| High severity | {high_total} | {high_7d} | — |

---

## By Rule (all-time)

| Rule | Count |
|---|---|
{by_rule_all}
## By Rule (last 7 days)

| Rule | Count |
|---|---|
{by_rule_7d}
## By Source

| Source | Count |
|---|---|
{by_source_all}
## By Severity

| Severity | Count |
|---|---|
{by_sev_all}
## By Agent

| Agent | Count |
|---|---|
{by_agent_all}
---

## Last 10 Violations (newest first)

| Timestamp | Severity | Agent | Rule | Detail (truncated) |
|---|---|---|---|---|
{last10_block}

---

*Run `bash infra/hooks/conduct-stats.sh --md` to refresh. Run `--check` for automated breach detection.*
"""

with open(out_path, "w", encoding="utf-8") as fh:
    fh.write(content)

print(f"conduct-stats --md: wrote {out_path}")
MD_PY
}

# ── Dispatch ──────────────────────────────────────────────────────────────────

if [[ $CHECK_MODE -eq 1 ]]; then
  run_check
elif [[ $MD_MODE -eq 1 ]]; then
  run_md
elif [[ $DREAM_MODE -eq 1 ]]; then
  if [[ "$_IMPL" == "jq" ]]; then
    run_jq_dream
  else
    run_python_dream
  fi
else
  if [[ "$_IMPL" == "jq" ]]; then
    run_jq_full
  else
    run_python_full
  fi
fi

exit 0
