"""Generate _brain_api/ from _brain_index/.

SBAP v1.0 — query endpoints agents call BEFORE reading raw files.

Usage:
    python3 build/tools/build_brain_api.py

Reads _brain_index/ + _agent_state/_registry.json, writes:
- _brain_api/_manifest.json
- _brain_api/canonical/<type>/<key>.json
- _brain_api/account/<client>/<endpoint>.json
- _brain_api/bid/<bid-id>/<endpoint>.json
- _brain_api/changes/since_<ts>.json
- _brain_api/agent/<agent>/scope.json

TODO: most endpoints below are stubs returning {} pending Phase 9/10/15/19 outputs.
"""
from __future__ import annotations

import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


VAULT = Path(os.environ.get("VAULT_ROOT") or (_ for _ in ()).throw(SystemExit("Set VAULT_ROOT to your vault path")))
INDEX = VAULT / "_brain_index"
API = VAULT / "_brain_api"
AGENT_STATE = VAULT / "_agent_state"


def utcnow() -> str:
    return datetime.now(timezone.utc).isoformat()


def safe_load(path: Path, default):
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return default


def build_manifest(agents: list[dict]) -> dict:
    return {
        "sbap_version": "1.0",
        "generated": utcnow(),
        "endpoints": {
            "canonical/<type>/<key>.json": "Canonical block for a type+key (e.g. exec_summary/vertical__ai_qa__enterprise)",
            "account/<client>/brief.json": "Composed live brief",
            "account/<client>/known_signals.json": "Signals already in vault (dedup ref)",
            "account/<client>/win_patterns.json": "Phase 9 patterns (TODO: not yet generated)",
            "bid/_open.json": "All bids not in Won/Lost",
            "bid/<bid-id>/status.json": "Bid composed state",
            "bid/<bid-id>/recommended_blocks.json": "Learning-engine picks (TODO)",
            "changes/since_<unix_ts>.json": "Vault delta after timestamp",
            "agent/<agent>/scope.json": "Read/write scope per registered agent",
        },
        "registered_agents": [a["agent_name"] for a in agents],
    }


def build_agent_scopes(agents: list[dict]) -> None:
    agent_dir = API / "agent"
    agent_dir.mkdir(parents=True, exist_ok=True)
    for a in agents:
        d = agent_dir / a["agent_name"]
        d.mkdir(exist_ok=True)
        scope = {
            "agent_name": a["agent_name"],
            "version": a.get("version", "1.0"),
            "status": a.get("status", "unknown"),
            "scope": a.get("scope", {}),
            "max_sensitivity": a.get("max_sensitivity", "internal"),
            "schedule": a.get("schedule", "on-demand"),
            "generated": utcnow(),
        }
        (d / "scope.json").write_text(json.dumps(scope, indent=2))


def build_bid_endpoints() -> int:
    """For each open bid in _brain_index/bids/_open.json, write a status.json."""
    open_data = safe_load(INDEX / "bids" / "_open.json", {"bids": []})
    bid_dir = API / "bid"
    bid_dir.mkdir(parents=True, exist_ok=True)

    # Top-level _open mirror (so agents can hit _brain_api/bid/_open.json directly)
    (bid_dir / "_open.json").write_text(json.dumps(open_data, indent=2))

    n = 0
    for b in open_data.get("bids", []):
        bd = bid_dir / b["bid_id"]
        bd.mkdir(exist_ok=True)
        status = {
            "bid_id": b["bid_id"],
            "client": b["client"],
            "stage": b["stage"],
            "value": b["value"],
            "deadline": b["deadline"],
            "probability": b["probability"],
            "owner": b["owner"],
            "opened": b["opened"],
            "generated": utcnow(),
        }
        (bd / "status.json").write_text(json.dumps(status, indent=2))
        # Stubs for TODO endpoints
        for stub in ("recommended_blocks", "compliance_gaps", "similar", "risk_score"):
            stub_path = bd / f"{stub}.json"
            if not stub_path.exists():
                stub_path.write_text(json.dumps({
                    "_todo": f"Generated by Phase 9/19 — pending infrastructure.",
                    "bid_id": b["bid_id"],
                    "data": None,
                }, indent=2))
        n += 1
    return n


def _parse_frontmatter(text: str) -> dict:
    """Extract YAML-like frontmatter from a markdown file (simple key: value only)."""
    fm: dict = {}
    if not text.startswith("---"):
        return fm
    end = text.find("---", 3)
    if end == -1:
        return fm
    block = text[3:end]
    for line in block.splitlines():
        m = re.match(r"^(\w[\w_-]*):\s*(.+)$", line.strip())
        if m:
            key, val = m.group(1), m.group(2).strip()
            # Strip inline YAML list brackets if present
            if val.startswith("[") and val.endswith("]"):
                val = [v.strip().strip('"\'') for v in val[1:-1].split(",") if v.strip()]
            fm[key] = val
    return fm


def _brief_excerpt(text: str, max_chars: int = 200) -> str:
    """Return the first blockquote or first non-empty paragraph after frontmatter."""
    # Skip frontmatter
    if text.startswith("---"):
        end = text.find("---", 3)
        text = text[end + 3:] if end != -1 else text
    for line in text.splitlines():
        line = line.strip()
        if line.startswith(">"):
            return line.lstrip("> ").strip()[:max_chars]
        if line and not line.startswith("#"):
            return line[:max_chars]
    return ""


def build_account_briefs() -> int:
    """For each folder in Clients/, parse _brief.md and emit brief.json + known_signals stub.

    Sources:
      - Clients/<slug>/_brief.md        — frontmatter + first blockquote/paragraph
      - Clients/<slug>/_stakeholders.md — existence check only (path ref)
      - Clients/<slug>/_last-touchpoint.md — existence check only (path ref)

    Writes:
      - _brain_api/account/<slug>/brief.json
      - _brain_api/account/<slug>/known_signals.json  (stub if not already present)
    """
    clients_dir = VAULT / "Clients"
    account_dir = API / "account"
    account_dir.mkdir(parents=True, exist_ok=True)

    if not clients_dir.exists():
        return 0

    n = 0
    for client_folder in sorted(clients_dir.iterdir()):
        if not client_folder.is_dir():
            continue
        slug = client_folder.name
        brief_md = client_folder / "_brief.md"
        if not brief_md.exists():
            continue

        text = brief_md.read_text(encoding="utf-8")
        fm = _parse_frontmatter(text)
        excerpt = _brief_excerpt(text)

        # Resolve optional companion files
        stakeholders_path = client_folder / "_stakeholders.md"
        touchpoint_path = client_folder / "_last-touchpoint.md"

        brief = {
            "slug": slug,
            "name": fm.get("client") or fm.get("partner") or slug,
            "type": fm.get("type", "client-brief"),
            "industry": fm.get("industry"),
            "stage": fm.get("stage"),
            "last_touchpoint": fm.get("last_touch"),
            "excerpt": excerpt,
            "stakeholders_ref": f"Clients/{slug}/_stakeholders.md" if stakeholders_path.exists() else None,
            "touchpoint_log_ref": f"Clients/{slug}/_last-touchpoint.md" if touchpoint_path.exists() else None,
            "meetings_link": "Meetings/recaps",
            "brief_source": f"Clients/{slug}/_brief.md",
            "tags": fm.get("tags", []),
            "generated": utcnow(),
        }

        out_dir = account_dir / slug
        out_dir.mkdir(exist_ok=True)
        (out_dir / "brief.json").write_text(json.dumps(brief, indent=2))

        # Stub known_signals only if it doesn't exist yet
        signals_path = out_dir / "known_signals.json"
        if not signals_path.exists():
            signals_path.write_text(json.dumps({
                "_todo": "Populated by Phase 9 signal-extraction pipeline.",
                "slug": slug,
                "signals": [],
            }, indent=2))

        n += 1
    return n


def build_canonical_stubs() -> None:
    """Create directory tree for canonical blocks. Actual canonicals filled by build_brain_index."""
    canonical = API / "canonical"
    for kind in ("exec_summary", "capability_statement", "case_study",
                 "compliance_response", "email_template", "pricing_pattern"):
        d = canonical / kind
        d.mkdir(parents=True, exist_ok=True)
        readme = d / "_README.md"
        if not readme.exists():
            readme.write_text(
                f"# Canonical {kind.replace('_', ' ')} blocks\n\n"
                f"Generated by build_brain_index.py once Content Library is populated.\n"
                f"Currently empty — TODO Phase 4.\n"
            )


def main() -> int:
    API.mkdir(exist_ok=True)
    registry = safe_load(AGENT_STATE / "_registry.json", {"agents": []})
    agents = registry.get("agents", [])

    manifest = build_manifest(agents)
    (API / "_manifest.json").write_text(json.dumps(manifest, indent=2))

    build_agent_scopes(agents)
    n_bids = build_bid_endpoints()
    n_accounts = build_account_briefs()
    build_canonical_stubs()

    # Empty changes endpoint
    (API / "changes").mkdir(exist_ok=True)
    (API / "changes" / "_README.md").write_text(
        "# Change feed endpoints\n\n"
        "`since_<unix_ts>.json` files generated incrementally by Phase 4.5 "
        "incremental rebuild. Currently empty.\n"
    )

    print(f"Built {API}")
    print(f"  registered agents:    {len(agents)}")
    print(f"  bid endpoints:        {n_bids}")
    print(f"  account briefs:       {n_accounts}")
    print(f"  canonical scaffolds:  exec_summary, capability_statement, case_study, compliance_response, email_template, pricing_pattern")
    return 0


if __name__ == "__main__":
    sys.exit(main())
